### ISSUE TITLE
pip installation error for django-materializecss-form 1.1.13

### ISSUE THREAD

**Issue by amj23897** [kalwalkden/django-materializecss-form#33]
```
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qLVeiA/django-materializecss-form/setup.py", line 8, in <module>
        with open("README.md", "r", encoding="utf-8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qLVeiA/django-materializecss-form/

```
Python Version: Python 2.7.15rc1
django-materializecss-form version 1.1.12 installs properly
PS : I am reporting an issue for the first time.

**Comment by kalwalkden** [comment]
@amj23897 1.1.13 discontinued support for python 2.7. Pipy should reflect this being python3 only now.
